set(_CATKIN_CURRENT_PACKAGE "sdu_frobit_remote")
set(sdu_frobit_remote_MAINTAINER "leon <leon@todo.todo>")
set(sdu_frobit_remote_DEPRECATED "")
set(sdu_frobit_remote_VERSION "0.0.0")
set(sdu_frobit_remote_BUILD_DEPENDS "roscpp" "rospy" "msgs" "smach" "smach_ros" "wiimote_interface" "generic_smach" "action_primitives")
set(sdu_frobit_remote_RUN_DEPENDS "roscpp" "rospy" "msgs" "smach" "smach_ros" "wiimote_interface" "generic_smach" "action_primitives")
set(sdu_frobit_remote_BUILDTOOL_DEPENDS "catkin")