set(_CATKIN_CURRENT_PACKAGE "sdu_frobit")
set(sdu_frobit_MAINTAINER "kjeld <kjeld@todo.todo>")
set(sdu_frobit_DEPRECATED "")
set(sdu_frobit_VERSION "0.0.0")
set(sdu_frobit_BUILD_DEPENDS "msgs" "roscpp" "rospy")
set(sdu_frobit_RUN_DEPENDS "msgs" "roscpp" "rospy")
set(sdu_frobit_BUILDTOOL_DEPENDS "catkin")